### ISSUE TITLE
运行起来了项目但是在点击可视化编辑页面打不开

### ISSUE THREAD

**Issue by cham-web** [entropy-cloud/nop-chaos#3]
运行起来了项目但是在点击可视化编辑页面打不开，找不到/amis-editor/index.html这个目录
![image](https://github.com/entropy-cloud/nop-chaos/assets/21168199/a0fdf49a-6ee7-403f-9fbd-99ccaf9bba8d)
![image](https://github.com/entropy-cloud/nop-chaos/assets/21168199/7762ea08-8aba-4441-924a-8add5192a512)

**Comment by entropy-cloud** [comment]
amis-editor代码比较多而且它使用的amis版本不一定是最新的，所以目前的做法是将amis-editor放到单独的package中，那个package可以单独编译测试，然后通过iframe嵌入到nop-site模块中使用。因此目前如果需要在线使用amis-editor，需要启用nop-entropy后端程序才行
